DROP DATABASE IF EXISTS ej5;
CREATE DATABASE IF NOT EXISTS ej5;

USE ej5;

CREATE TABLE IF NOT EXISTS Gnere(
idGnere INTEGER UNSIGNED PRIMARY KEY AUTO_INCREMENT,
gnere VARCHAR(255) 
);

DESCRIBE ej5.Gnere;

CREATE TABLE IF NOT EXISTS Album(
idAlbum INTEGER UNSIGNED PRIMARY KEY auto_increment,
albumName VARCHAR(255),
dataReleased DATETIME
);

DESCRIBE ej5.Album;


